<?php
/**
 * Athlete Results System - Menilo Theme Installation Wizard
 * Features: Menilo dashboard design, progress tracking, database creation/reset
 * Based on: Menilo CakePHP Admin & Dashboard Template
 */

session_start();

// Check if installation is already complete
$configFile = __DIR__ . '/config/database.php';
$installLockFile = __DIR__ . '/install/.installed';

if (file_exists($installLockFile) && !isset($_GET['force'])) {
    header('Location: index.php');
    exit;
}

// Get current step
$step = isset($_GET['step']) ? (int)$_GET['step'] : 1;
$action = isset($_POST['action']) ? $_POST['action'] : '';

// Handle form submissions
if ($action === 'check_database') {
    handleDatabaseCheck();
}
if ($action === 'create_database') {
    handleDatabaseCreation();
}
if ($action === 'import_schema') {
    handleSchemaImport();
}
if ($action === 'save_config') {
    handleConfigSave();
}

// API Response Functions
function handleDatabaseCheck() {
    header('Content-Type: application/json');
    $host = $_POST['db_host'] ?? 'localhost';
    $user = $_POST['db_user'] ?? '';
    $pass = $_POST['db_pass'] ?? '';
    
    try {
        $pdo = new PDO("mysql:host={$host}", $user, $pass);
        $_SESSION['db_config'] = compact('host', 'user', 'pass');
        echo json_encode(['success' => true, 'message' => 'Database connection successful', 'progress' => 25]);
    } catch (PDOException $e) {
        http_response_code(400);
        echo json_encode(['success' => false, 'message' => 'Connection failed: ' . $e->getMessage()]);
    }
    exit;
}

function handleDatabaseCreation() {
    header('Content-Type: application/json');
    $dbName = $_POST['db_name'] ?? '';
    $resetDb = isset($_POST['reset_db']) && $_POST['reset_db'] === '1';
    
    if (empty($dbName)) {
        http_response_code(400);
        echo json_encode(['success' => false, 'message' => 'Database name required']);
        exit;
    }
    
    $config = $_SESSION['db_config'] ?? [];
    $host = $config['host'] ?? 'localhost';
    $user = $config['user'] ?? '';
    $pass = $config['pass'] ?? '';
    
    try {
        $pdo = new PDO("mysql:host={$host}", $user, $pass);
        
        if ($resetDb) {
            $pdo->exec("DROP DATABASE IF EXISTS `{$dbName}`");
        }
        
        $pdo->exec("CREATE DATABASE IF NOT EXISTS `{$dbName}` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci");
        $_SESSION['db_config']['name'] = $dbName;
        
        echo json_encode(['success' => true, 'message' => 'Database created successfully', 'progress' => 50]);
    } catch (PDOException $e) {
        http_response_code(400);
        echo json_encode(['success' => false, 'message' => 'Error: ' . $e->getMessage()]);
    }
    exit;
}

function handleSchemaImport() {
    header('Content-Type: application/json');
    $config = $_SESSION['db_config'] ?? [];
    $host = $config['host'] ?? 'localhost';
    $user = $config['user'] ?? '';
    $pass = $config['pass'] ?? '';
    $dbName = $config['name'] ?? '';
    
    try {
        $pdo = new PDO("mysql:host={$host};dbname={$dbName};charset=utf8mb4", $user, $pass);
        
        $sqlFile = __DIR__ . '/install/database.sql';
        if (file_exists($sqlFile)) {
            $sql = file_get_contents($sqlFile);
            $pdo->exec($sql);
        }
        
        echo json_encode(['success' => true, 'message' => 'Database schema imported', 'progress' => 75]);
    } catch (PDOException $e) {
        http_response_code(400);
        echo json_encode(['success' => false, 'message' => 'Import error: ' . $e->getMessage()]);
    }
    exit;
}

function handleConfigSave() {
    header('Content-Type: application/json');
    $config = $_SESSION['db_config'] ?? [];
    
    $configContent = "<?php\n";
    $configContent .= "// Database configuration - Auto-generated by Menilo Installer\n";
    $configContent .= "define('DB_HOST', '{$config['host']}');\n";
    $configContent .= "define('DB_NAME', '{$config['name']}');\n";
    $configContent .= "define('DB_USER', '{$config['user']}');\n";
    $configContent .= "define('DB_PASS', '{$config['pass']}');\n";
    $configContent .= "define('DB_CHARSET', 'utf8mb4');\n\n";
    $configContent .= "// PDO Connection\n";
    $configContent .= "try {\n";
    $configContent .= "    \$pdo = new PDO('mysql:host=' . DB_HOST . ';dbname=' . DB_NAME . ';charset=utf8mb4', DB_USER, DB_PASS);\n";
    $configContent .= "    \$pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);\n";
    $configContent .= "} catch (PDOException \$e) {\n";
    $configContent .= "    die('Database connection failed: ' . \$e->getMessage());\n";
    $configContent .= "}\n";
    
    if (!is_dir(__DIR__ . '/config')) {
        mkdir(__DIR__ . '/config', 0755, true);
    }
    
    if (file_put_contents(__DIR__ . '/config/database.php', $configContent)) {
        @mkdir(__DIR__ . '/install', 0755, true);
        $lockData = [
            'installed_at' => date('Y-m-d H:i:s'),
            'database' => $config['name'],
            'version' => '1.0.0'
        ];
        file_put_contents(__DIR__ . '/install/.installed', json_encode($lockData));
        
        echo json_encode(['success' => true, 'message' => 'Configuration saved', 'progress' => 100]);
    } else {
        http_response_code(400);
        echo json_encode(['success' => false, 'message' => 'Failed to save configuration']);
    }
    exit;
}
?>
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Menilo - Installation Wizard</title>
    
    <style>
        :root {
            --primary-color: #667eea;
            --secondary-color: #764ba2;
            --menilo-gradient: linear-gradient(135deg, var(--primary-color) 0%, var(--secondary-color) 100%);
            --success-color: #10b981;
            --danger-color: #ef4444;
            --warning-color: #f59e0b;
            --info-color: #3b82f6;
        }

        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }

        body {
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            background: var(--menilo-gradient);
            min-height: 100vh;
            display: flex;
            align-items: center;
            justify-content: center;
            padding: 20px;
        }

        .menilo-container {
            background: white;
            border-radius: 12px;
            box-shadow: 0 20px 60px rgba(0, 0, 0, 0.3);
            max-width: 600px;
            width: 100%;
            overflow: hidden;
        }

        .menilo-header {
            background: var(--menilo-gradient);
            color: white;
            padding: 40px 30px;
            text-align: center;
        }

        .menilo-header h1 {
            font-size: 32px;
            margin-bottom: 10px;
            font-weight: 700;
        }

        .menilo-header p {
            font-size: 14px;
            opacity: 0.95;
        }

        .menilo-body {
            padding: 40px 30px;
            min-height: 400px;
        }

        .progress-bar {
            height: 8px;
            background: #e5e7eb;
            border-radius: 4px;
            overflow: hidden;
            margin-bottom: 30px;
        }

        .progress-fill {
            height: 100%;
            background: var(--menilo-gradient);
            width: 0%;
            transition: width 0.3s ease;
        }

        .form-group {
            margin-bottom: 20px;
        }

        .form-group label {
            display: block;
            margin-bottom: 8px;
            font-weight: 600;
            color: #374151;
            font-size: 14px;
        }

        .form-group input,
        .form-group select {
            width: 100%;
            padding: 12px;
            border: 2px solid #e5e7eb;
            border-radius: 8px;
            font-size: 14px;
            transition: border-color 0.3s;
        }

        .form-group input:focus,
        .form-group select:focus {
            outline: none;
            border-color: var(--primary-color);
            box-shadow: 0 0 0 3px rgba(102, 126, 234, 0.1);
        }

        .form-group input[type="checkbox"] {
            width: auto;
            margin-right: 8px;
        }

        .checkbox-label {
            display: flex;
            align-items: center;
            font-weight: 500;
            color: #4b5563;
        }

        .btn {
            display: inline-block;
            padding: 12px 28px;
            border: none;
            border-radius: 8px;
            font-weight: 600;
            cursor: pointer;
            transition: all 0.3s;
            font-size: 14px;
            text-decoration: none;
            text-align: center;
        }

        .btn-primary {
            background: var(--menilo-gradient);
            color: white;
            width: 100%;
            margin-top: 10px;
        }

        .btn-primary:hover {
            transform: translateY(-2px);
            box-shadow: 0 10px 20px rgba(102, 126, 234, 0.3);
        }

        .btn-primary:disabled,
        .btn-primary.loading {
            opacity: 0.7;
            cursor: not-allowed;
        }

        .alert {
            padding: 15px;
            border-radius: 8px;
            margin-bottom: 20px;
            font-size: 14px;
            border-left: 4px solid;
        }

        .alert-success {
            background: #d1fae5;
            color: #065f46;
            border-color: var(--success-color);
        }

        .alert-danger {
            background: #fee2e2;
            color: #7f1d1d;
            border-color: var(--danger-color);
        }

        .alert-info {
            background: #dbeafe;
            color: #1e3a8a;
            border-color: var(--info-color);
        }

        .step-header {
            margin-bottom: 30px;
        }

        .step-header h2 {
            font-size: 24px;
            color: #1f2937;
            margin-bottom: 8px;
        }

        .step-header p {
            color: #6b7280;
            font-size: 14px;
        }

        .step-content {
            display: none;
        }

        .step-content.active {
            display: block;
            animation: fadeIn 0.3s ease;
        }

        @keyframes fadeIn {
            from {
                opacity: 0;
            }
            to {
                opacity: 1;
            }
        }

        .spinner {
            display: inline-block;
            width: 16px;
            height: 16px;
            border: 3px solid rgba(255, 255, 255, 0.3);
            border-radius: 50%;
            border-top-color: white;
            animation: spin 1s linear infinite;
            margin-right: 8px;
        }

        @keyframes spin {
            to {
                transform: rotate(360deg);
            }
        }

        .hidden {
            display: none !important;
        }

        .menilo-footer {
            background: #f9fafb;
            padding: 20px 30px;
            border-top: 1px solid #e5e7eb;
            text-align: center;
            font-size: 12px;
            color: #6b7280;
        }

        .menilo-footer a {
            color: var(--primary-color);
            text-decoration: none;
        }

        .status-icon {
            display: inline-block;
            width: 20px;
            height: 20px;
            border-radius: 50%;
            margin-right: 8px;
            vertical-align: middle;
        }

        .status-success {
            background: var(--success-color);
            color: white;
        }

        .status-pending {
            background: #e5e7eb;
            color: #9ca3af;
        }

        .step-info {
            background: #f9fafb;
            padding: 15px;
            border-radius: 8px;
            margin-bottom: 20px;
            border-left: 4px solid var(--primary-color);
        }

        .step-info strong {
            color: #1f2937;
        }

        .step-info p {
            margin: 5px 0;
            font-size: 13px;
            color: #6b7280;
        }
    </style>
</head>

<body>
    <div class="menilo-container">
        <div class="menilo-header">
            <h1>🚀 Menilo Installation</h1>
            <p>Athlete Results System - Setup Wizard</p>
        </div>

        <div class="menilo-body">
            <div class="progress-bar">
                <div class="progress-fill" id="progressFill" style="width: 0%;"></div>
            </div>

            <!-- Step 1: Welcome -->
            <div class="step-content active" id="step1">
                <div class="step-header">
                    <h2>Welcome to Menilo Installation</h2>
                    <p>Let's get your system up and running</p>
                </div>

                <div class="step-info">
                    <strong>ℹ️ What will happen:</strong>
                    <p>1. Test database connection</p>
                    <p>2. Create or reset database</p>
                    <p>3. Import database schema</p>
                    <p>4. Save configuration</p>
                </div>

                <button class="btn btn-primary" onclick="showStep(2)">Start Installation →</button>
            </div>

            <!-- Step 2: Database Credentials -->
            <div class="step-content" id="step2">
                <div class="step-header">
                    <h2>Database Credentials</h2>
                    <p>Enter your MySQL connection details</p>
                </div>

                <div id="credAlert"></div>

                <div class="form-group">
                    <label for="dbHost">Database Host</label>
                    <input type="text" id="dbHost" value="localhost" placeholder="localhost or your server">
                </div>

                <div class="form-group">
                    <label for="dbUser">Database Username</label>
                    <input type="text" id="dbUser" placeholder="e.g., root or database_user">
                </div>

                <div class="form-group">
                    <label for="dbPass">Database Password</label>
                    <input type="password" id="dbPass" placeholder="Your database password">
                </div>

                <button class="btn btn-primary" onclick="testConnection()">
                    <span class="spinner hidden" id="testSpinner"></span>
                    <span id="testText">Test Connection</span>
                </button>
            </div>

            <!-- Step 3: Database Setup -->
            <div class="step-content" id="step3">
                <div class="step-header">
                    <h2>Database Setup</h2>
                    <p>Create or select your database</p>
                </div>

                <div id="createAlert"></div>

                <div class="form-group">
                    <label for="dbName">Database Name</label>
                    <input type="text" id="dbName" value="athletes" placeholder="e.g., athletes or athlete_db">
                </div>

                <div class="form-group">
                    <label class="checkbox-label">
                        <input type="checkbox" id="resetDb">
                        <span>Reset existing database (deletes all data)</span>
                    </label>
                </div>

                <button class="btn btn-primary" onclick="createDatabase()">
                    <span class="spinner hidden" id="createSpinner"></span>
                    <span id="createText">Create Database</span>
                </button>
            </div>

            <!-- Step 4: Import Schema -->
            <div class="step-content" id="step4">
                <div class="step-header">
                    <h2>Import Database Schema</h2>
                    <p>Setting up tables and initial data</p>
                </div>

                <div id="importStatus" style="padding: 15px; background: #f0f9ff; border-radius: 8px; color: #0c4a6e;">
                    <span class="spinner"></span> Importing database schema...
                </div>

                <div id="importAlert" style="margin-top: 15px;"></div>
            </div>

            <!-- Step 5: Save Configuration -->
            <div class="step-content" id="step5">
                <div class="step-header">
                    <h2>Save Configuration</h2>
                    <p>Finalizing installation</p>
                </div>

                <div id="saveStatus" style="padding: 15px; background: #f0f9ff; border-radius: 8px; color: #0c4a6e;">
                    <span class="spinner"></span> Saving configuration...
                </div>

                <div id="saveAlert" style="margin-top: 15px;"></div>
            </div>

            <!-- Step 6: Complete -->
            <div class="step-content" id="step6">
                <div class="step-header">
                    <h2>✓ Installation Complete!</h2>
                    <p>Your system is ready to use</p>
                </div>

                <div class="step-info">
                    <strong>🎉 Success:</strong>
                    <p>Database configured and schema imported</p>
                    <p>Your Menilo dashboard is ready!</p>
                </div>

                <button class="btn btn-primary" onclick="window.location.href='index.php'">
                    Go to Dashboard →
                </button>
            </div>
        </div>

        <div class="menilo-footer">
            <p>Developed by <strong>Mwamiri Computers</strong> | support@mwamiri.co.ke</p>
            <p>Powered by Menilo CakePHP Admin & Dashboard Template</p>
        </div>
    </div>

    <script>
        function showStep(stepNum) {
            document.querySelectorAll('.step-content').forEach(el => el.classList.remove('active'));
            document.getElementById('step' + stepNum).classList.add('active');
            updateProgress((stepNum - 1) * 16);
        }

        function updateProgress(percentage) {
            document.getElementById('progressFill').style.width = percentage + '%';
        }

        function showAlert(message, type = 'danger', elementId = 'credAlert') {
            const alertClass = 'alert-' + type;
            document.getElementById(elementId).innerHTML = 
                `<div class="alert ${alertClass}">${message}</div>`;
        }

        function testConnection() {
            const host = document.getElementById('dbHost').value;
            const user = document.getElementById('dbUser').value;
            const pass = document.getElementById('dbPass').value;

            if (!user) {
                showAlert('Username is required', 'danger', 'credAlert');
                return;
            }

            document.getElementById('testSpinner').classList.remove('hidden');
            document.getElementById('testText').textContent = 'Testing...';

            fetch('installer-menilo.php', {
                method: 'POST',
                headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
                body: 'action=check_database&db_host=' + encodeURIComponent(host) +
                      '&db_user=' + encodeURIComponent(user) +
                      '&db_pass=' + encodeURIComponent(pass)
            })
            .then(r => r.json())
            .then(data => {
                document.getElementById('testSpinner').classList.add('hidden');
                document.getElementById('testText').textContent = 'Test Connection';

                if (data.success) {
                    showAlert('✓ Connection successful!', 'success', 'credAlert');
                    updateProgress(25);
                    setTimeout(() => showStep(3), 1500);
                } else {
                    showAlert(data.message, 'danger', 'credAlert');
                }
            })
            .catch(err => {
                document.getElementById('testSpinner').classList.add('hidden');
                document.getElementById('testText').textContent = 'Test Connection';
                showAlert('Connection error: ' + err.message, 'danger', 'credAlert');
            });
        }

        function createDatabase() {
            const dbName = document.getElementById('dbName').value;
            const resetDb = document.getElementById('resetDb').checked;

            if (!dbName) {
                showAlert('Database name is required', 'danger', 'createAlert');
                return;
            }

            document.getElementById('createSpinner').classList.remove('hidden');
            document.getElementById('createText').textContent = 'Creating...';

            fetch('installer-menilo.php', {
                method: 'POST',
                headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
                body: 'action=create_database&db_name=' + encodeURIComponent(dbName) +
                      '&reset_db=' + (resetDb ? '1' : '0')
            })
            .then(r => r.json())
            .then(data => {
                document.getElementById('createSpinner').classList.add('hidden');
                document.getElementById('createText').textContent = 'Create Database';

                if (data.success) {
                    showAlert('✓ Database created successfully!', 'success', 'createAlert');
                    updateProgress(50);
                    setTimeout(() => {
                        showStep(4);
                        importSchema();
                    }, 1500);
                } else {
                    showAlert(data.message, 'danger', 'createAlert');
                }
            })
            .catch(err => {
                document.getElementById('createSpinner').classList.add('hidden');
                document.getElementById('createText').textContent = 'Create Database';
                showAlert('Error: ' + err.message, 'danger', 'createAlert');
            });
        }

        function importSchema() {
            fetch('installer-menilo.php', {
                method: 'POST',
                headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
                body: 'action=import_schema'
            })
            .then(r => r.json())
            .then(data => {
                document.getElementById('importStatus').innerHTML = 
                    '<div class="alert alert-success">✓ ' + data.message + '</div>';
                updateProgress(75);
                setTimeout(() => {
                    showStep(5);
                    saveConfiguration();
                }, 1500);
            })
            .catch(err => {
                document.getElementById('importStatus').innerHTML = 
                    '<div class="alert alert-danger">Error: ' + err.message + '</div>';
            });
        }

        function saveConfiguration() {
            fetch('installer-menilo.php', {
                method: 'POST',
                headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
                body: 'action=save_config'
            })
            .then(r => r.json())
            .then(data => {
                document.getElementById('saveStatus').innerHTML = 
                    '<div class="alert alert-success">✓ ' + data.message + '</div>';
                updateProgress(100);
                setTimeout(() => showStep(6), 1500);
            })
            .catch(err => {
                document.getElementById('saveStatus').innerHTML = 
                    '<div class="alert alert-danger">Error: ' + err.message + '</div>';
            });
        }

        // Auto-start on load
        window.addEventListener('load', () => {
            updateProgress(0);
        });
    </script>
</body>

</html>
